### ISSUE TITLE
Opens a new file with a different editor

### ISSUE THREAD

**Issue by c2v4** [amitdev/PMD-Intellij#17] opened 2015-06-09 15:39 UTC
When double clicked on rule violation in PMD window, it opens a file not taking into consideration that file was already opened. File is opened in different editor window

**Comment by amitdev** [comment] 2015-06-22 14:42
Which version/platform are you using? It reuses the open editor tab for me.

**Comment by amitdev** [comment] 2015-11-10 10:47
Closing since I'm not able to reproduce this issue.

**Closed by amitdev** 2015-11-10 10:47 UTC
